apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-jenkinsintegration
spec:
  selector:
    matchLabels:
      app: nginxintegration
  replicas: 2
  template:
    metadata:
      labels:
        app: nginxintegration
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
